### ISSUE TITLE
trialFunction

### ISSUE THREAD

**Issue by wzinke** [HukLab/PLDAPS#15]
I had some trouble solving an error in the runTrial function when it executes: 
   `tfh=str2func(p.trial.pldaps.trialFunction);`
p.trial.pldaps.trialFunction was not defined. I realized that this assignment was not done in any of the pldaps main functions but instead in the tutorial trialfunction (plain) when it is first called. 

Why not per default make an assignment like:
   `p.defaultParameters.pldaps.trialFunction = p.trial.session.experimentSetupFile;`
  
I can understand the reason for the flexibility to define trialFunction in a more dynamic way but I think assigning the experimentSetupFile as default would support more simplicity in handling the code.

**Comment by jonaskn** [comment]
Hi,

I fear that that default would create more confusion than it solves as the standard use (at least in our lab) is for the trialFunction to be different from the experimentSetupFile.

The trialFunction is something generic that takes parameters to show something. The experimentSetupFile is to define those parameters.
Unless it is something really small with very limited use (e.g. the demo in pldaps or some of my hardware timing test stimuli), I think this default would create the bad incentive to copy the trialFunction for each set of parameters you might want to run, instead of just creating a new experimentSetupFile with the new parameters. 

I realize that part of the confusion might come from the way the plain example is use and I might change that. But at least in the readme is does say that

> %p.defaultParameters.pldaps.trialFunction='plain';   
%I.e. in this example case, we use the same function to setup the experiment parameters and to calculate the stimulus
%this is typically not the case later, when you have one stimulus file and several experiments that you define that use the sae stimulus code

I considered making pldapsDefaultTrialFunction the default trialFunction, but there are still a few dependencies to clean up before that is an option.

**Comment by wzinke** [comment]
OK. Since all the examples I saw did do this assignment in the function itself I thought this was a relict from previous pldaps incarnations. The documentation seems indeed to be a bit confusion at some points, not making clear the strict separation of the experimental setup and trial definition, and that the trial function has to be specified explicitly.

For our own convenience I added the line to our session set-up function. I rather reduce the number of files and redundancies. However, took a while before I figured out why my trial function did not get assigned. But yes, re-reading the readme it says it at several instances.
