### ISSUE TITLE
isField vs isfield in pldapsDefaultTrialFunction 

### ISSUE THREAD

**Issue by lpl1977** [HukLab/PLDAPS#18]
Hello

I had to change isField to isfield in a few places in the default trial function after I merged the most recent commit into my fork.  I'm not sure if use of isField is by design but it seemed to be a legacy issue given the use of isfield elsewhere in the code.

Also, what's up with a special case for 'eyeW' now?  My aesthetic sense is not happy...

LL

**Comment by jcbyts** [comment]
isField is a subfunction in pldaps. It is necessary for things to run correctly. It should not be isfield. 

I made the same mistake when I started using Jonas' pldaps. isField doesn't work when the required paths aren't added correctly.

I don't know about the eyeW bug. I'll check later.

**Comment by jcbyts** [comment]
@jonaskn You know, since this is the third or fourth time someone has modified isField to isfield, maybe we should change the name of the function.

**Comment by lpl1977** [comment]
Thanks @jcbyts, but I've used pldaps for a long time now and know the difference.  Also, I hate to quibble, but isField is a method of the params object, not a subfunction in pldaps.

in the pldapsDefaultTrialFunction, starting with line 39, the relevant code is:
case p.trial.pldaps.trialStates.experimentPostOpenScreen
            if ~isfield(p.trial.(sn), 'eyeW')
                p.trial.(sn).eyeW = 8;
            end
            if ~isField(p.trial,'event')
                defaultBitNames(p);
            end
            %defaultColors get's called by pldaps.openScreen since overlay2
            %got introduced
            if ~isField(p.defaultParameters.display,'humanCLUT')
                defaultColors(p);
end

In these cases isField is being called on arguments which are not params objects.  It's not a static method of params so it's not even the right way to call isField even if that's what was supposed to be here.  It needs to be isfield, not isField.

I'm creating a pull request for my edits (which I've verified to work correctly whereas the isField version won't because of the wrong argument types).

In all honesty I don't mind if isField keeps its name, it would be too much trouble to change and it would most likely break backwards compatibility.

**Comment by jcbyts** [comment]
@lpl1977 You're right. Sorry, I just assumed that it was the same mistake. Yes, isField is method of params, and inside pldapsDefaultTrialFunction, 'trial' is a struct so it is incorrect to call isField on it. However, defaultParameters should still be a params object, right? 

Looks like the suspicious lines were added in commit d363394960d4dc86d34eb62a20cc25db74724e75

I'll double check the pull request on my end, but it looks good.

**Comment by jonaskn** [comment]
@lpl1977, yes 
`~isField(p.defaultParameters.display,'humanCLUT')`
 looks like a bug. Don't know how that slipped through.
`~isField(p.trial,'event')` 
is correct though, and using isfield would create a silent undetected mistake ( isfield(p.trial,'event') returns 0 even if that field exists. ).

Do you want to correct your pull request? Also why does your pull request show that many other commits in it?

@jcbyts I agree that the naming causes confusions, should be either rename the function and/or also make it work with structs so that iField can always be used?

As to eyeW: I agree that it is not pretty, but with this all dependencies to the defaultTrialVariables etc should hopefully be captured, which makes adding modules easier and ensures that, if pldapsDefaultTrialFucntion is not used under .stimulus but as it's own module e.g. under .pldaps, the pldapsDefaultFunction does not use parameters in that other module space.
Note that with the new version you can run an `@plain` equivalent by calling e.g.:
```
settingsStruct.pldaps.stateFunction.name='pldapsDefaultTrialFunction';
settingsStruct.pldaps.stateFunction.acceptsLocationInput=true;
settingsStruct.pldaps.stateFunction.order=-eps;
settingsStruct.pldaps.use=true;
 
p=pldaps('test', settingsStruct);
p.run;
```
thanks catching this!
jonas

**Comment by lpl1977** [comment]
@jonaskn I fixed the pull request.  Thanks!

The other commits are there because of my fumbling with git, but afaik it isn't going to break anything...

**Comment by Phenomenal-Cat** [comment]
FYI there's also an 'isField' on line 120 of openScreen.m that looks like it should be 'isfield'.

**Comment by jonaskn** [comment]
Those uses of 'isField' in openScreen are correct. Btw: most current development is in the openreception branch.
