### ISSUE TITLE
States and modular trial function 

### ISSUE THREAD

**Issue by lpl1977** [HukLab/PLDAPS#23]
My modules seem to run in all states. Not a problem since I use switch for the appropriate state and the order is correct for what I’ve coded. Just wondering if I’m doing something wrong though because requested states is getting ignored.

**Comment by czuba** [comment]
Odd...I'm not able to replicate that issue. 

Setting up a module with `dv` as the settingsStruct I use to create a pldaps object:
```sn = 'moduleName';
dv.(sn).use = true;
dv.(sn).stateFunction.name = 'moduleFxn';
dv.(sn).stateFunction.acceptsLocationInput = true;
dv.(sn).stateFunction.order = 0;
dv.(sn).stateFunction.requestedStates = struct('frameDraw',true,...
                                               'trialItiDraw',true,...
                                               'experimentPostOpenScreen',true',...
                                               'experimentCleanUp',true);
```

If I then set `.requestedStates.frameDraw` to  `false`  , that module no longer is drawn during the trial. However, it does still appear during inter-trial intervals (...a relatively new state called `trialItiDraw`), confirming that the module is still otherwise functioning.

Double check your code...perhaps you're missing the last 's' on .requestedState**s**?

If that doesn't solve it, post a simple module & example setup code that replicates the issue you're seeing.

**Comment by lpl1977** [comment]
Hiya

Thanks for the sample object.  The problem was that I was specifying my requested states with a cell array rather than a struct.  I’m not sure where I got the impression that this was a legit way to specify them, but now that I’ve fixed that issue I get expected behavior.

When I was reading through getModules.m to check this part, I noticed a couple of comments that I had some thoughts on:

First, I use 0 as my default reference for order and negative for before this and positive for after this.  I can see why some people might find it confusing to have negative trialStates ignored but not negative module order, but it seems like one of the multitude of things that is initially confusing about PLDAPS and then becomes clear with some use.  And I make use of it.

Second, and this one’s important, I still use a p.trial.pdlaps.trialFunction alongside some modules.  I’m counting on that case towards the end where it gets put into the list of modules with the appropriate fields.  So I need that special case for backwards compatibility.
