### ISSUE TITLE
PsychPortAudio on Linux 

### ISSUE THREAD

**Issue by jcbyts** [HukLab/PLDAPS#4]
Kept hitting a PTB internal error when I tried to open a second PsychPortAudio device on the same sound card. See IssuePsychPortAudioLinux branch

**Comment by jcbyts** [comment]
PTB-INFO: Using specially modified PortAudio engine, based on offical version: PortAudio V19-devel
PTB-INFO: New audio device with handle 0 opened as PortAudio stream:
PTB-INFO: For 1 channels Playback: Audio subsystem is ALSA, Audio device name is HDA Intel PCH: ALC1150 Digital (hw:1,1)
PTB-INFO: Real samplerate 44100.000000 Hz. Input latency 0.000000 msecs, Output latency 9.977324 msecs.
PTB-ERROR: Desired audio parameters for device 1 unsupported by audio device. PortAudio reports this error: Device unavailable 
PTB-ERROR: This could be, e.g., due to an unsupported combination of audio sample rate, audio channel allocation, or audio sample format.
PTB-ERROR: On Linux you may be able to use ALSA audio converter plugins to make this work.
INTERNAL PSYCHTOOLBOX ERROR
    error:                PsychError_system
    general description:  Error reported by a system call
    specific description: Failed to open PortAudio audio device due to unsupported combination of audio parameters.
    module name:          PsychPortAudio
    subfunction call:     Open
    file name:            Common/PsychPortAudio/PsychPortAudio.c
    function name:        PSYCHPORTAUDIOOpen
    line number:          2417

The error is about "unsupported combination of audio parameters.", however, this error only gets thrown when opening a second PsychPortAudio device, regardless of what the parameters are

**Comment by jonaskn** [comment]
@jcbyts I think the solution in the IssuePsychPortAudioLinux is good. @lpl1977 tested it and identified three things we might want to improve before merging with openreception:
- Volume Setting
  you are setting the master Volume to 0.5. Is that necessary? If not, I would suggest making it an optional parameter:
  `if ~isempty(p.trial.sound.masterVolume),
  PsychPortAudio('Volume', p.trial.sound.master, p.trial.sound.masterVolume);
  end`
  We can set p.trial.sound.masterVolume=0.5; as the default parameter.
- Sampling rates
  You are currently setting up the master with it's default sampling rate. Because all other slaves have the same sampling rate, this might cause unexpected behavior if the slave file has a different sampling rate. Should we have the option to resample the files to the masters frequency?
- Device ID warning
  The new implementation actually caused problems on a Linux systems with a device id that allowed a device to be opened multiple time (i.e. where the old implementation worked fine). Changing to a different device solved this. I think this is ok, but we should have a note in the help or at least in the commit message that warns users that this might happen and how to solve this.

**Comment by jcbyts** [comment]
@jonaskn 
- Volume Setting
  It's totally not necessary. In fact, we could just cut it until someone wants to add volume as a parameter. I think I just had that copied from the PTB demo code.
- Sampling rates
  Yea. I didn't have a good solution to this. How easy is it to implement that resampling?
- Device ID warning
  Huh. Not sure I follow. Is there a version of this that doesn't cause a problem. I've found that if pldaps crashes and doesn't close the master, then I can't reopen it without calling.

`PsychPortAudio('Close', 0);`

I should probably add that to the close routine when pldaps crashes. Haven't gotten to it yet

**Comment by jcbyts** [comment]
Closing issue because it the fix has been merged in to open reception
